version: '3.1'

services: 
  mysql:
    restart: always
#    expose:
#      - "3306"
#      - "33060"
#    ports:
#      - "3306:3306"
#      - "33060:33060"
    image: mysql/mysql-server:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks:
      - cybro-network
    
  cybroscgiserver:
    restart: always
    expose:
      - "4000"
      - "8442/udp"
    ports:
      - "4000:4000"
      - "8442:8442/udp"
    hostname: cybroscgiserver
    volumes:
      - "./cybroscgiserver/config/:/opt/config/"
      - "./cybroscgiserver/core/:/opt/transfer/"
      - "./cybroscgiserver/data/:/opt/data/"
    build: cybroscgiserver
    networks:
      - cybro-network

networks:
  cybro-network:
    driver: bridge
